import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LibraryManagementSystem.java
 *
 * Created on 9 Oct, 2017, 1:30:41 PM
 */

/**
 *
 * @author Manas Trivedi
 */
public class LibraryManagementSystem extends javax.swing.JFrame {
Connection con=null;
Statement stmt=null;
ResultSet rs=null;
DefaultTableModel tm=null;
    /** Creates new form LibraryManagementSystem */
    public LibraryManagementSystem() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookDetailsFrame = new javax.swing.JFrame();
        bookDetailsPanel = new javax.swing.JPanel();
        bookIdLabel = new javax.swing.JLabel();
        TitleLable = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        publisherLabel = new javax.swing.JLabel();
        isbnLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        purchaseDateLabel = new javax.swing.JLabel();
        bookID1TextField = new javax.swing.JTextField();
        title1TextField = new javax.swing.JTextField();
        author1TextField = new javax.swing.JTextField();
        publisher1TextField = new javax.swing.JTextField();
        ISBN1TextField = new javax.swing.JTextField();
        price1TextField = new javax.swing.JTextField();
        purchaseDate1TextField = new javax.swing.JTextField();
        add1Button = new javax.swing.JButton();
        update1Button = new javax.swing.JButton();
        delete1Button = new javax.swing.JButton();
        enquire1Button = new javax.swing.JButton();
        clear1Button = new javax.swing.JButton();
        return1Button = new javax.swing.JButton();
        bookDetailsBackgroundlabel = new javax.swing.JLabel();
        memberDetailsFrame = new javax.swing.JFrame();
        memberDetailsPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        memberID2TextField = new javax.swing.JTextField();
        name2TextField = new javax.swing.JTextField();
        class2ComboBox = new javax.swing.JComboBox();
        section2ComboBox = new javax.swing.JComboBox();
        enquire2Button = new javax.swing.JButton();
        add2Button = new javax.swing.JButton();
        update2Button = new javax.swing.JButton();
        delete2Button = new javax.swing.JButton();
        clear2Button = new javax.swing.JButton();
        return2Button = new javax.swing.JButton();
        memberdetailsbackgroundLabel = new javax.swing.JLabel();
        issueBookFrame = new javax.swing.JFrame();
        bookIssuePanel = new javax.swing.JPanel();
        return3Button = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        bookID3TextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        memberID3TextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        dateOfIssue3TextField = new javax.swing.JTextField();
        today3Button = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        title3OutputLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        author3OutputLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        name3OutputLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        class3OutputLabel = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        section3OutputLabel = new javax.swing.JLabel();
        issueBook3Button = new javax.swing.JButton();
        clear3Button = new javax.swing.JButton();
        BookIssueBackgroundLabel = new javax.swing.JLabel();
        returnBookFrame = new javax.swing.JFrame();
        bookReceiptPanel = new javax.swing.JPanel();
        bookID4TextField = new javax.swing.JTextField();
        dateOfReturn4TextField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        return4Button = new javax.swing.JButton();
        today4Button = new javax.swing.JButton();
        title4OutputLabel = new javax.swing.JLabel();
        author4OutputLabel = new javax.swing.JLabel();
        name4OutputLabel = new javax.swing.JLabel();
        class4OutputLabel = new javax.swing.JLabel();
        section4OutputLabel = new javax.swing.JLabel();
        dateOfIssue4OutputLabel = new javax.swing.JLabel();
        returnBook4Button = new javax.swing.JButton();
        clear4Button = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        memberID4OutputLabel = new javax.swing.JLabel();
        bookReceiptBackgroundLabel = new javax.swing.JLabel();
        historyFrame = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        history5Table = new javax.swing.JTable();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        bookID5TextField = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        memberID5TextField = new javax.swing.JTextField();
        showSpecificHistory5Button = new javax.swing.JButton();
        showEntireHistory5Button = new javax.swing.JButton();
        clear5Button = new javax.swing.JButton();
        backToMainMenu5Button = new javax.swing.JButton();
        historyBackgroundLabel = new javax.swing.JLabel();
        bookDetailsButton = new javax.swing.JButton();
        memberDetailsButton = new javax.swing.JButton();
        issueBookButton = new javax.swing.JButton();
        returnBookButton = new javax.swing.JButton();
        historyButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        mainMenuBackgroundLabel = new javax.swing.JLabel();

        bookDetailsFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        bookDetailsFrame.setTitle("Book Details");
        bookDetailsFrame.setBounds(new java.awt.Rectangle(0, 0, 816, 538));
        bookDetailsFrame.setForeground(new java.awt.Color(153, 153, 255));
        bookDetailsFrame.setIconImage(new ImageIcon("D:\\iconImage.png").getImage());
        bookDetailsFrame.setMaximizedBounds(new java.awt.Rectangle(0, 0, 700, 425));
        bookDetailsFrame.setMinimumSize(new java.awt.Dimension(816, 538));
        bookDetailsFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                bookDetailsFrameWindowActivated(evt);
            }
        });
        bookDetailsFrame.getContentPane().setLayout(null);

        bookDetailsPanel.setBackground(new java.awt.Color(255, 51, 102));
        bookDetailsPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bookDetailsPanel.setMaximumSize(new java.awt.Dimension(800, 520));
        bookDetailsPanel.setLayout(null);

        bookIdLabel.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        bookIdLabel.setForeground(new java.awt.Color(0, 0, 255));
        bookIdLabel.setText("Book ID:");
        bookDetailsPanel.add(bookIdLabel);
        bookIdLabel.setBounds(130, 50, 100, 25);

        TitleLable.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        TitleLable.setForeground(new java.awt.Color(0, 0, 255));
        TitleLable.setText("Title:");
        bookDetailsPanel.add(TitleLable);
        TitleLable.setBounds(130, 90, 80, 25);

        authorLabel.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        authorLabel.setForeground(new java.awt.Color(0, 0, 255));
        authorLabel.setText("Author:");
        bookDetailsPanel.add(authorLabel);
        authorLabel.setBounds(130, 130, 90, 25);

        publisherLabel.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        publisherLabel.setForeground(new java.awt.Color(0, 0, 255));
        publisherLabel.setText("Publisher:");
        bookDetailsPanel.add(publisherLabel);
        publisherLabel.setBounds(130, 170, 100, 25);

        isbnLabel.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        isbnLabel.setForeground(new java.awt.Color(0, 0, 255));
        isbnLabel.setText("ISBN:");
        bookDetailsPanel.add(isbnLabel);
        isbnLabel.setBounds(130, 210, 80, 25);

        priceLabel.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        priceLabel.setForeground(new java.awt.Color(0, 0, 255));
        priceLabel.setText("Price:");
        bookDetailsPanel.add(priceLabel);
        priceLabel.setBounds(130, 290, 100, 25);

        purchaseDateLabel.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        purchaseDateLabel.setForeground(new java.awt.Color(0, 0, 255));
        purchaseDateLabel.setText("Purchase Date:");
        bookDetailsPanel.add(purchaseDateLabel);
        purchaseDateLabel.setBounds(130, 250, 136, 25);

        bookID1TextField.setFont(new java.awt.Font("Book Antiqua", 0, 20));
        bookID1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookID1TextFieldActionPerformed(evt);
            }
        });
        bookDetailsPanel.add(bookID1TextField);
        bookID1TextField.setBounds(300, 50, 170, 31);

        title1TextField.setFont(new java.awt.Font("Book Antiqua", 0, 20));
        title1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                title1TextFieldActionPerformed(evt);
            }
        });
        bookDetailsPanel.add(title1TextField);
        title1TextField.setBounds(300, 90, 380, 31);

        author1TextField.setFont(new java.awt.Font("Book Antiqua", 0, 20));
        author1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                author1TextFieldActionPerformed(evt);
            }
        });
        bookDetailsPanel.add(author1TextField);
        author1TextField.setBounds(300, 130, 380, 31);

        publisher1TextField.setFont(new java.awt.Font("Book Antiqua", 0, 20));
        publisher1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisher1TextFieldActionPerformed(evt);
            }
        });
        bookDetailsPanel.add(publisher1TextField);
        publisher1TextField.setBounds(300, 170, 380, 31);

        ISBN1TextField.setFont(new java.awt.Font("Book Antiqua", 0, 20));
        ISBN1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISBN1TextFieldActionPerformed(evt);
            }
        });
        bookDetailsPanel.add(ISBN1TextField);
        ISBN1TextField.setBounds(300, 210, 170, 31);

        price1TextField.setFont(new java.awt.Font("Book Antiqua", 0, 20));
        price1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price1TextFieldActionPerformed(evt);
            }
        });
        bookDetailsPanel.add(price1TextField);
        price1TextField.setBounds(300, 290, 170, 31);

        purchaseDate1TextField.setFont(new java.awt.Font("Book Antiqua", 0, 20));
        purchaseDate1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseDate1TextFieldActionPerformed(evt);
            }
        });
        bookDetailsPanel.add(purchaseDate1TextField);
        purchaseDate1TextField.setBounds(300, 250, 170, 31);

        add1Button.setBackground(new java.awt.Color(255, 102, 102));
        add1Button.setFont(new java.awt.Font("Book Antiqua", 1, 24));
        add1Button.setForeground(new java.awt.Color(0, 0, 153));
        add1Button.setText("Add");
        add1Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add1Button.setMaximumSize(new java.awt.Dimension(250, 51));
        add1Button.setMinimumSize(new java.awt.Dimension(250, 51));
        add1Button.setPreferredSize(new java.awt.Dimension(250, 51));
        add1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ButtonActionPerformed(evt);
            }
        });
        bookDetailsPanel.add(add1Button);
        add1Button.setBounds(180, 360, 100, 40);

        update1Button.setBackground(new java.awt.Color(255, 102, 102));
        update1Button.setFont(new java.awt.Font("Book Antiqua", 1, 24));
        update1Button.setForeground(add1Button.getForeground());
        update1Button.setText("Update");
        update1Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ButtonActionPerformed(evt);
            }
        });
        bookDetailsPanel.add(update1Button);
        update1Button.setBounds(290, 360, 100, 40);
        update1Button.getAccessibleContext().setAccessibleName("");

        delete1Button.setBackground(new java.awt.Color(255, 102, 102));
        delete1Button.setFont(new java.awt.Font("Book Antiqua", 1, 24));
        delete1Button.setForeground(add1Button.getForeground());
        delete1Button.setText("Delete");
        delete1Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delete1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ButtonActionPerformed(evt);
            }
        });
        bookDetailsPanel.add(delete1Button);
        delete1Button.setBounds(400, 360, 100, 40);
        delete1Button.getAccessibleContext().setAccessibleName("");

        enquire1Button.setBackground(new java.awt.Color(255, 102, 102));
        enquire1Button.setFont(new java.awt.Font("Book Antiqua", 1, 24));
        enquire1Button.setForeground(add1Button.getForeground());
        enquire1Button.setText("Enquire");
        enquire1Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        enquire1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enquire1ButtonActionPerformed(evt);
            }
        });
        bookDetailsPanel.add(enquire1Button);
        enquire1Button.setBounds(510, 360, 100, 40);
        enquire1Button.getAccessibleContext().setAccessibleName("");

        clear1Button.setBackground(new java.awt.Color(255, 102, 102));
        clear1Button.setFont(new java.awt.Font("Book Antiqua", 1, 24));
        clear1Button.setForeground(add1Button.getForeground());
        clear1Button.setText("Clear");
        clear1Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear1ButtonActionPerformed(evt);
            }
        });
        bookDetailsPanel.add(clear1Button);
        clear1Button.setBounds(210, 410, 100, 40);

        return1Button.setBackground(new java.awt.Color(255, 102, 102));
        return1Button.setFont(new java.awt.Font("Book Antiqua", 1, 24));
        return1Button.setForeground(add1Button.getForeground());
        return1Button.setText("Back to Main Menu");
        return1Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        return1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return1ButtonActionPerformed(evt);
            }
        });
        bookDetailsPanel.add(return1Button);
        return1Button.setBounds(320, 410, 260, 40);

        bookDetailsBackgroundlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Books-Background-Hd-Wallpaper.jpg"))); // NOI18N
        bookDetailsBackgroundlabel.setMaximumSize(new java.awt.Dimension(800, 500));
        bookDetailsBackgroundlabel.setMinimumSize(new java.awt.Dimension(800, 500));
        bookDetailsBackgroundlabel.setPreferredSize(new java.awt.Dimension(800, 500));
        bookDetailsPanel.add(bookDetailsBackgroundlabel);
        bookDetailsBackgroundlabel.setBounds(0, 0, 800, 500);

        bookDetailsFrame.getContentPane().add(bookDetailsPanel);
        bookDetailsPanel.setBounds(0, 0, 810, 520);

        bookDetailsFrame.getAccessibleContext().setAccessibleDescription("Member Details");

        memberDetailsFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        memberDetailsFrame.setTitle("Member Details");
        memberDetailsFrame.setIconImage(new ImageIcon("D:\\iconImage.png").getImage());
        memberDetailsFrame.setMinimumSize(new java.awt.Dimension(854, 558));
        memberDetailsFrame.getContentPane().setLayout(null);

        memberDetailsPanel.setMinimumSize(new java.awt.Dimension(400, 300));
        memberDetailsPanel.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setText("Member ID:");
        jLabel8.setFocusable(false);
        jLabel8.setMaximumSize(new java.awt.Dimension(70, 22));
        jLabel8.setMinimumSize(new java.awt.Dimension(70, 22));
        jLabel8.setPreferredSize(new java.awt.Dimension(70, 22));
        jLabel8.setRequestFocusEnabled(false);
        jLabel8.setVerifyInputWhenFocusTarget(false);
        memberDetailsPanel.add(jLabel8);
        jLabel8.setBounds(40, 110, 120, 30);

        jLabel9.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel9.setForeground(new java.awt.Color(255, 255, 204));
        jLabel9.setText("Name:");
        jLabel9.setMaximumSize(new java.awt.Dimension(70, 22));
        jLabel9.setMinimumSize(new java.awt.Dimension(70, 22));
        jLabel9.setPreferredSize(new java.awt.Dimension(70, 22));
        memberDetailsPanel.add(jLabel9);
        jLabel9.setBounds(40, 150, 130, 30);

        jLabel10.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel10.setForeground(new java.awt.Color(255, 255, 204));
        jLabel10.setText("Class:");
        jLabel10.setMaximumSize(new java.awt.Dimension(70, 22));
        jLabel10.setMinimumSize(new java.awt.Dimension(70, 22));
        jLabel10.setPreferredSize(new java.awt.Dimension(70, 22));
        memberDetailsPanel.add(jLabel10);
        jLabel10.setBounds(40, 190, 130, 30);

        jLabel11.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel11.setForeground(new java.awt.Color(255, 255, 204));
        jLabel11.setText("Section:");
        jLabel11.setMaximumSize(new java.awt.Dimension(70, 22));
        jLabel11.setMinimumSize(new java.awt.Dimension(70, 22));
        jLabel11.setPreferredSize(new java.awt.Dimension(70, 22));
        memberDetailsPanel.add(jLabel11);
        jLabel11.setBounds(40, 230, 90, 30);

        memberID2TextField.setFont(new java.awt.Font("Book Antiqua", 0, 20));
        memberID2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberID2TextFieldActionPerformed(evt);
            }
        });
        memberDetailsPanel.add(memberID2TextField);
        memberID2TextField.setBounds(170, 110, 100, 30);

        name2TextField.setFont(new java.awt.Font("Book Antiqua", 0, 20));
        name2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name2TextFieldActionPerformed(evt);
            }
        });
        memberDetailsPanel.add(name2TextField);
        name2TextField.setBounds(170, 150, 350, 30);

        class2ComboBox.setFont(new java.awt.Font("Book Antiqua", 0, 20));
        class2ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12", "11", "10", "9", "8", "7", "6" }));
        class2ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                class2ComboBoxActionPerformed(evt);
            }
        });
        memberDetailsPanel.add(class2ComboBox);
        class2ComboBox.setBounds(170, 190, 100, 30);

        section2ComboBox.setFont(new java.awt.Font("Book Antiqua", 0, 20));
        section2ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z" }));
        section2ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                section2ComboBoxActionPerformed(evt);
            }
        });
        memberDetailsPanel.add(section2ComboBox);
        section2ComboBox.setBounds(170, 230, 100, 30);

        enquire2Button.setBackground(new java.awt.Color(200, 3, 51));
        enquire2Button.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        enquire2Button.setForeground(new java.awt.Color(255, 255, 204));
        enquire2Button.setText("Enquire");
        enquire2Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        enquire2Button.setMaximumSize(new java.awt.Dimension(250, 51));
        enquire2Button.setMinimumSize(new java.awt.Dimension(250, 51));
        enquire2Button.setPreferredSize(new java.awt.Dimension(250, 51));
        enquire2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enquire2ButtonActionPerformed(evt);
            }
        });
        memberDetailsPanel.add(enquire2Button);
        enquire2Button.setBounds(390, 310, 130, 40);

        add2Button.setBackground(new java.awt.Color(200, 3, 51));
        add2Button.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        add2Button.setForeground(new java.awt.Color(255, 255, 204));
        add2Button.setText("Add");
        add2Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add2Button.setMaximumSize(new java.awt.Dimension(250, 51));
        add2Button.setMinimumSize(new java.awt.Dimension(250, 51));
        add2Button.setPreferredSize(new java.awt.Dimension(250, 51));
        add2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add2ButtonActionPerformed(evt);
            }
        });
        memberDetailsPanel.add(add2Button);
        add2Button.setBounds(40, 310, 100, 40);

        update2Button.setBackground(new java.awt.Color(200, 3, 51));
        update2Button.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        update2Button.setForeground(new java.awt.Color(255, 255, 204));
        update2Button.setText("Update");
        update2Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update2Button.setMaximumSize(new java.awt.Dimension(250, 51));
        update2Button.setMinimumSize(new java.awt.Dimension(250, 51));
        update2Button.setPreferredSize(new java.awt.Dimension(250, 51));
        update2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update2ButtonActionPerformed(evt);
            }
        });
        memberDetailsPanel.add(update2Button);
        update2Button.setBounds(150, 310, 110, 40);

        delete2Button.setBackground(new java.awt.Color(200, 3, 51));
        delete2Button.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        delete2Button.setForeground(new java.awt.Color(255, 255, 204));
        delete2Button.setText("Delete");
        delete2Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delete2Button.setMaximumSize(new java.awt.Dimension(250, 51));
        delete2Button.setMinimumSize(new java.awt.Dimension(250, 51));
        delete2Button.setPreferredSize(new java.awt.Dimension(250, 51));
        delete2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete2ButtonActionPerformed(evt);
            }
        });
        memberDetailsPanel.add(delete2Button);
        delete2Button.setBounds(270, 310, 110, 40);

        clear2Button.setBackground(new java.awt.Color(200, 3, 51));
        clear2Button.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        clear2Button.setForeground(new java.awt.Color(255, 255, 204));
        clear2Button.setText("Clear");
        clear2Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear2Button.setMaximumSize(new java.awt.Dimension(250, 51));
        clear2Button.setMinimumSize(new java.awt.Dimension(250, 51));
        clear2Button.setPreferredSize(new java.awt.Dimension(250, 51));
        clear2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear2ButtonActionPerformed(evt);
            }
        });
        memberDetailsPanel.add(clear2Button);
        clear2Button.setBounds(70, 360, 140, 40);

        return2Button.setBackground(new java.awt.Color(200, 3, 51));
        return2Button.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        return2Button.setForeground(new java.awt.Color(255, 255, 204));
        return2Button.setText("Back to Main Menu");
        return2Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        return2Button.setMaximumSize(new java.awt.Dimension(250, 51));
        return2Button.setMinimumSize(new java.awt.Dimension(250, 51));
        return2Button.setPreferredSize(new java.awt.Dimension(250, 51));
        return2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return2ButtonActionPerformed(evt);
            }
        });
        memberDetailsPanel.add(return2Button);
        return2Button.setBounds(220, 360, 270, 40);

        memberdetailsbackgroundLabel.setFont(new java.awt.Font("Tahoma", 0, 18));
        memberdetailsbackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image7.jpg"))); // NOI18N
        memberDetailsPanel.add(memberdetailsbackgroundLabel);
        memberdetailsbackgroundLabel.setBounds(0, 0, 840, 710);

        memberDetailsFrame.getContentPane().add(memberDetailsPanel);
        memberDetailsPanel.setBounds(0, 0, 870, 520);

        issueBookFrame.setTitle("Issue Book");
        issueBookFrame.setIconImage(new ImageIcon("D:\\iconImage.png").getImage());
        issueBookFrame.setMinimumSize(new java.awt.Dimension(896, 539));
        issueBookFrame.getContentPane().setLayout(null);

        bookIssuePanel.setLayout(null);

        return3Button.setBackground(new java.awt.Color(0, 204, 255));
        return3Button.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        return3Button.setForeground(new java.awt.Color(0, 0, 153));
        return3Button.setText("Back to Main Menu");
        return3Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        return3Button.setMaximumSize(new java.awt.Dimension(250, 51));
        return3Button.setMinimumSize(new java.awt.Dimension(250, 51));
        return3Button.setPreferredSize(new java.awt.Dimension(250, 51));
        return3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return3ButtonActionPerformed(evt);
            }
        });
        bookIssuePanel.add(return3Button);
        return3Button.setBounds(330, 370, 240, 40);
        return3Button.getAccessibleContext().setAccessibleName("");

        jLabel12.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("Book ID:");
        bookIssuePanel.add(jLabel12);
        jLabel12.setBounds(70, 60, 130, 22);

        bookID3TextField.setFont(new java.awt.Font("Book Antiqua", 0, 20));
        bookID3TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookID3TextFieldActionPerformed(evt);
            }
        });
        bookIssuePanel.add(bookID3TextField);
        bookID3TextField.setBounds(220, 60, 120, 22);

        jLabel13.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("Member ID:");
        jLabel13.setMaximumSize(new java.awt.Dimension(71, 22));
        jLabel13.setMinimumSize(new java.awt.Dimension(71, 22));
        jLabel13.setPreferredSize(new java.awt.Dimension(71, 22));
        bookIssuePanel.add(jLabel13);
        jLabel13.setBounds(70, 90, 130, 22);

        memberID3TextField.setFont(new java.awt.Font("Book Antiqua", 0, 20));
        memberID3TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberID3TextFieldActionPerformed(evt);
            }
        });
        bookIssuePanel.add(memberID3TextField);
        memberID3TextField.setBounds(220, 90, 120, 22);

        jLabel14.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel14.setForeground(new java.awt.Color(0, 0, 153));
        jLabel14.setText("Date of Issue:");
        jLabel14.setMaximumSize(new java.awt.Dimension(71, 22));
        jLabel14.setMinimumSize(new java.awt.Dimension(71, 22));
        jLabel14.setPreferredSize(new java.awt.Dimension(71, 22));
        bookIssuePanel.add(jLabel14);
        jLabel14.setBounds(70, 120, 140, 22);

        dateOfIssue3TextField.setFont(new java.awt.Font("Book Antiqua", 0, 20));
        dateOfIssue3TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateOfIssue3TextFieldActionPerformed(evt);
            }
        });
        bookIssuePanel.add(dateOfIssue3TextField);
        dateOfIssue3TextField.setBounds(220, 120, 120, 22);

        today3Button.setBackground(new java.awt.Color(0, 204, 255));
        today3Button.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        today3Button.setForeground(new java.awt.Color(0, 0, 153));
        today3Button.setText("Today");
        today3Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        today3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                today3ButtonActionPerformed(evt);
            }
        });
        bookIssuePanel.add(today3Button);
        today3Button.setBounds(350, 120, 80, 30);

        jLabel15.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel15.setForeground(new java.awt.Color(0, 0, 153));
        jLabel15.setText("Title:");
        jLabel15.setMaximumSize(new java.awt.Dimension(71, 22));
        jLabel15.setMinimumSize(new java.awt.Dimension(71, 22));
        jLabel15.setPreferredSize(new java.awt.Dimension(71, 22));
        bookIssuePanel.add(jLabel15);
        jLabel15.setBounds(70, 170, 120, 22);

        title3OutputLabel.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        title3OutputLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bookIssuePanel.add(title3OutputLabel);
        title3OutputLabel.setBounds(220, 170, 350, 22);

        jLabel17.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel17.setForeground(new java.awt.Color(0, 0, 153));
        jLabel17.setText("Author:");
        jLabel17.setMaximumSize(new java.awt.Dimension(71, 22));
        jLabel17.setMinimumSize(new java.awt.Dimension(71, 22));
        jLabel17.setPreferredSize(new java.awt.Dimension(71, 22));
        bookIssuePanel.add(jLabel17);
        jLabel17.setBounds(70, 200, 120, 22);

        author3OutputLabel.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        author3OutputLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bookIssuePanel.add(author3OutputLabel);
        author3OutputLabel.setBounds(220, 200, 350, 22);

        jLabel19.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel19.setForeground(new java.awt.Color(0, 0, 153));
        jLabel19.setText("Name:");
        jLabel19.setMaximumSize(new java.awt.Dimension(71, 22));
        jLabel19.setMinimumSize(new java.awt.Dimension(71, 22));
        jLabel19.setPreferredSize(new java.awt.Dimension(71, 22));
        bookIssuePanel.add(jLabel19);
        jLabel19.setBounds(70, 230, 120, 22);

        name3OutputLabel.setBackground(new java.awt.Color(255, 204, 204));
        name3OutputLabel.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        name3OutputLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bookIssuePanel.add(name3OutputLabel);
        name3OutputLabel.setBounds(220, 230, 350, 22);

        jLabel21.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel21.setForeground(new java.awt.Color(0, 0, 153));
        jLabel21.setText("Class:");
        jLabel21.setMaximumSize(new java.awt.Dimension(71, 22));
        jLabel21.setMinimumSize(new java.awt.Dimension(71, 22));
        jLabel21.setPreferredSize(new java.awt.Dimension(71, 22));
        bookIssuePanel.add(jLabel21);
        jLabel21.setBounds(70, 260, 110, 22);

        class3OutputLabel.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        class3OutputLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bookIssuePanel.add(class3OutputLabel);
        class3OutputLabel.setBounds(220, 260, 120, 22);

        jLabel23.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel23.setForeground(new java.awt.Color(0, 0, 153));
        jLabel23.setText("Section:");
        jLabel23.setMaximumSize(new java.awt.Dimension(71, 22));
        jLabel23.setMinimumSize(new java.awt.Dimension(71, 22));
        jLabel23.setPreferredSize(new java.awt.Dimension(71, 22));
        bookIssuePanel.add(jLabel23);
        jLabel23.setBounds(70, 290, 90, 22);

        section3OutputLabel.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        section3OutputLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bookIssuePanel.add(section3OutputLabel);
        section3OutputLabel.setBounds(220, 290, 120, 22);

        issueBook3Button.setBackground(new java.awt.Color(0, 204, 255));
        issueBook3Button.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        issueBook3Button.setForeground(new java.awt.Color(0, 0, 153));
        issueBook3Button.setText("Issue Book");
        issueBook3Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        issueBook3Button.setMaximumSize(new java.awt.Dimension(250, 51));
        issueBook3Button.setMinimumSize(new java.awt.Dimension(250, 51));
        issueBook3Button.setPreferredSize(new java.awt.Dimension(250, 51));
        issueBook3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBook3ButtonActionPerformed(evt);
            }
        });
        bookIssuePanel.add(issueBook3Button);
        issueBook3Button.setBounds(70, 370, 140, 40);
        issueBook3Button.getAccessibleContext().setAccessibleName("");

        clear3Button.setBackground(new java.awt.Color(0, 204, 255));
        clear3Button.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        clear3Button.setForeground(new java.awt.Color(0, 0, 153));
        clear3Button.setText("Clear");
        clear3Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear3Button.setMaximumSize(new java.awt.Dimension(250, 51));
        clear3Button.setMinimumSize(new java.awt.Dimension(250, 51));
        clear3Button.setPreferredSize(new java.awt.Dimension(250, 51));
        clear3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear3ButtonActionPerformed(evt);
            }
        });
        bookIssuePanel.add(clear3Button);
        clear3Button.setBounds(220, 370, 100, 40);
        clear3Button.getAccessibleContext().setAccessibleName("");

        BookIssueBackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image10.jpg"))); // NOI18N
        bookIssuePanel.add(BookIssueBackgroundLabel);
        BookIssueBackgroundLabel.setBounds(0, 0, 890, 500);

        issueBookFrame.getContentPane().add(bookIssuePanel);
        bookIssuePanel.setBounds(0, 0, 880, 510);

        returnBookFrame.setTitle("Return Book");
        returnBookFrame.setIconImage(new ImageIcon("D:\\iconImage.png").getImage());
        returnBookFrame.setMinimumSize(new java.awt.Dimension(764, 484));
        returnBookFrame.getContentPane().setLayout(null);

        bookReceiptPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bookReceiptPanel.setLayout(null);

        bookID4TextField.setFont(new java.awt.Font("Book Antiqua", 0, 20));
        bookID4TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookID4TextFieldActionPerformed(evt);
            }
        });
        bookReceiptPanel.add(bookID4TextField);
        bookID4TextField.setBounds(260, 50, 120, 30);

        dateOfReturn4TextField.setFont(new java.awt.Font("Book Antiqua", 0, 20));
        dateOfReturn4TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateOfReturn4TextFieldActionPerformed(evt);
            }
        });
        bookReceiptPanel.add(dateOfReturn4TextField);
        dateOfReturn4TextField.setBounds(260, 90, 170, 30);

        jLabel25.setBackground(new java.awt.Color(204, 255, 255));
        jLabel25.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel25.setForeground(new java.awt.Color(102, 0, 102));
        jLabel25.setText("Book ID:");
        bookReceiptPanel.add(jLabel25);
        jLabel25.setBounds(100, 60, 130, 22);

        jLabel26.setBackground(new java.awt.Color(204, 255, 255));
        jLabel26.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel26.setForeground(new java.awt.Color(102, 0, 102));
        jLabel26.setText("Date of Return:");
        jLabel26.setMaximumSize(new java.awt.Dimension(71, 22));
        jLabel26.setMinimumSize(new java.awt.Dimension(71, 22));
        jLabel26.setPreferredSize(new java.awt.Dimension(71, 22));
        bookReceiptPanel.add(jLabel26);
        jLabel26.setBounds(100, 90, 150, 30);

        jLabel27.setBackground(new java.awt.Color(204, 255, 255));
        jLabel27.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel27.setForeground(new java.awt.Color(102, 0, 102));
        jLabel27.setText("Title:");
        jLabel27.setMaximumSize(new java.awt.Dimension(71, 22));
        jLabel27.setMinimumSize(new java.awt.Dimension(71, 22));
        jLabel27.setPreferredSize(new java.awt.Dimension(71, 22));
        bookReceiptPanel.add(jLabel27);
        jLabel27.setBounds(100, 140, 130, 22);

        jLabel28.setBackground(new java.awt.Color(204, 255, 255));
        jLabel28.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel28.setForeground(new java.awt.Color(102, 0, 102));
        jLabel28.setText("Author:");
        jLabel28.setMaximumSize(new java.awt.Dimension(71, 22));
        jLabel28.setMinimumSize(new java.awt.Dimension(71, 22));
        jLabel28.setPreferredSize(new java.awt.Dimension(71, 22));
        bookReceiptPanel.add(jLabel28);
        jLabel28.setBounds(100, 170, 130, 22);

        jLabel29.setBackground(new java.awt.Color(204, 255, 255));
        jLabel29.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel29.setForeground(new java.awt.Color(102, 0, 102));
        jLabel29.setText("Name:");
        jLabel29.setMaximumSize(new java.awt.Dimension(71, 22));
        jLabel29.setMinimumSize(new java.awt.Dimension(71, 22));
        jLabel29.setPreferredSize(new java.awt.Dimension(71, 22));
        bookReceiptPanel.add(jLabel29);
        jLabel29.setBounds(100, 230, 130, 22);

        jLabel30.setBackground(new java.awt.Color(204, 255, 255));
        jLabel30.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel30.setForeground(new java.awt.Color(102, 0, 102));
        jLabel30.setText("Class:");
        jLabel30.setMaximumSize(new java.awt.Dimension(71, 22));
        jLabel30.setMinimumSize(new java.awt.Dimension(71, 22));
        jLabel30.setPreferredSize(new java.awt.Dimension(71, 22));
        bookReceiptPanel.add(jLabel30);
        jLabel30.setBounds(100, 260, 130, 22);

        jLabel31.setBackground(new java.awt.Color(204, 255, 255));
        jLabel31.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel31.setForeground(new java.awt.Color(102, 0, 102));
        jLabel31.setText("Section:");
        jLabel31.setMaximumSize(new java.awt.Dimension(71, 22));
        jLabel31.setMinimumSize(new java.awt.Dimension(71, 22));
        jLabel31.setPreferredSize(new java.awt.Dimension(71, 22));
        bookReceiptPanel.add(jLabel31);
        jLabel31.setBounds(100, 290, 130, 22);

        jLabel32.setBackground(new java.awt.Color(204, 255, 255));
        jLabel32.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel32.setForeground(new java.awt.Color(102, 0, 102));
        jLabel32.setText("Date of Issue:");
        jLabel32.setMaximumSize(new java.awt.Dimension(71, 22));
        jLabel32.setMinimumSize(new java.awt.Dimension(71, 22));
        jLabel32.setPreferredSize(new java.awt.Dimension(71, 22));
        bookReceiptPanel.add(jLabel32);
        jLabel32.setBounds(100, 320, 130, 22);

        return4Button.setBackground(new java.awt.Color(255, 153, 255));
        return4Button.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        return4Button.setForeground(new java.awt.Color(102, 0, 102));
        return4Button.setText("Back to Main Menu");
        return4Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        return4Button.setMaximumSize(new java.awt.Dimension(250, 51));
        return4Button.setMinimumSize(new java.awt.Dimension(250, 51));
        return4Button.setPreferredSize(new java.awt.Dimension(250, 51));
        return4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return4ButtonActionPerformed(evt);
            }
        });
        bookReceiptPanel.add(return4Button);
        return4Button.setBounds(390, 370, 220, 40);

        today4Button.setBackground(new java.awt.Color(255, 153, 255));
        today4Button.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        today4Button.setForeground(new java.awt.Color(102, 0, 102));
        today4Button.setText("Today");
        today4Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        today4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                today4ButtonActionPerformed(evt);
            }
        });
        bookReceiptPanel.add(today4Button);
        today4Button.setBounds(440, 90, 100, 30);

        title4OutputLabel.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        title4OutputLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bookReceiptPanel.add(title4OutputLabel);
        title4OutputLabel.setBounds(260, 140, 350, 22);

        author4OutputLabel.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        author4OutputLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        author4OutputLabel.setPreferredSize(new java.awt.Dimension(30, 100));
        bookReceiptPanel.add(author4OutputLabel);
        author4OutputLabel.setBounds(260, 170, 350, 22);

        name4OutputLabel.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        name4OutputLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        name4OutputLabel.setPreferredSize(new java.awt.Dimension(30, 100));
        bookReceiptPanel.add(name4OutputLabel);
        name4OutputLabel.setBounds(260, 230, 350, 22);

        class4OutputLabel.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        class4OutputLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        class4OutputLabel.setPreferredSize(new java.awt.Dimension(30, 100));
        bookReceiptPanel.add(class4OutputLabel);
        class4OutputLabel.setBounds(260, 260, 130, 22);

        section4OutputLabel.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        section4OutputLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        section4OutputLabel.setPreferredSize(new java.awt.Dimension(30, 100));
        bookReceiptPanel.add(section4OutputLabel);
        section4OutputLabel.setBounds(260, 290, 130, 22);

        dateOfIssue4OutputLabel.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        dateOfIssue4OutputLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dateOfIssue4OutputLabel.setPreferredSize(new java.awt.Dimension(30, 100));
        bookReceiptPanel.add(dateOfIssue4OutputLabel);
        dateOfIssue4OutputLabel.setBounds(260, 320, 130, 22);

        returnBook4Button.setBackground(new java.awt.Color(255, 153, 255));
        returnBook4Button.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        returnBook4Button.setForeground(new java.awt.Color(102, 0, 102));
        returnBook4Button.setText("Return Book");
        returnBook4Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        returnBook4Button.setMaximumSize(new java.awt.Dimension(250, 51));
        returnBook4Button.setMinimumSize(new java.awt.Dimension(250, 51));
        returnBook4Button.setPreferredSize(new java.awt.Dimension(250, 51));
        returnBook4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBook4ButtonActionPerformed(evt);
            }
        });
        bookReceiptPanel.add(returnBook4Button);
        returnBook4Button.setBounds(100, 370, 160, 40);

        clear4Button.setBackground(new java.awt.Color(255, 153, 255));
        clear4Button.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        clear4Button.setForeground(new java.awt.Color(102, 0, 102));
        clear4Button.setText("Clear");
        clear4Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear4Button.setMaximumSize(new java.awt.Dimension(250, 51));
        clear4Button.setMinimumSize(new java.awt.Dimension(250, 51));
        clear4Button.setPreferredSize(new java.awt.Dimension(250, 51));
        clear4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear4ButtonActionPerformed(evt);
            }
        });
        bookReceiptPanel.add(clear4Button);
        clear4Button.setBounds(280, 370, 90, 40);

        jLabel39.setBackground(new java.awt.Color(204, 255, 255));
        jLabel39.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel39.setForeground(new java.awt.Color(102, 0, 102));
        jLabel39.setText("Member ID:");
        jLabel39.setMaximumSize(new java.awt.Dimension(71, 22));
        jLabel39.setMinimumSize(new java.awt.Dimension(71, 22));
        jLabel39.setPreferredSize(new java.awt.Dimension(71, 22));
        bookReceiptPanel.add(jLabel39);
        jLabel39.setBounds(100, 200, 130, 22);

        memberID4OutputLabel.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        memberID4OutputLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        memberID4OutputLabel.setPreferredSize(new java.awt.Dimension(30, 100));
        bookReceiptPanel.add(memberID4OutputLabel);
        memberID4OutputLabel.setBounds(260, 200, 350, 22);

        bookReceiptBackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image4.jpg"))); // NOI18N
        bookReceiptPanel.add(bookReceiptBackgroundLabel);
        bookReceiptBackgroundLabel.setBounds(0, 0, 750, 450);

        returnBookFrame.getContentPane().add(bookReceiptPanel);
        bookReceiptPanel.setBounds(-1, 0, 760, 460);

        historyFrame.setTitle("History");
        historyFrame.setIconImage(new ImageIcon("D:\\iconImage.png").getImage());
        historyFrame.setMinimumSize(new java.awt.Dimension(1105, 704));
        historyFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                historyFrameWindowActivated(evt);
            }
        });
        historyFrame.getContentPane().setLayout(null);

        history5Table.setBackground(new java.awt.Color(153, 153, 153));
        history5Table.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        history5Table.setForeground(new java.awt.Color(255, 255, 255));
        history5Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Title", "Member ID", "Name", "Date of Issue", "Date of Return"
            }
        ));
        history5Table.setGridColor(new java.awt.Color(255, 255, 255));
        history5Table.setRowHeight(30);
        history5Table.setRowMargin(5);
        jScrollPane1.setViewportView(history5Table);

        historyFrame.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 1070, 220);

        jLabel41.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Show history for:");
        historyFrame.getContentPane().add(jLabel41);
        jLabel41.setBounds(710, 300, 180, 25);

        jLabel42.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Book ID:");
        historyFrame.getContentPane().add(jLabel42);
        jLabel42.setBounds(710, 340, 82, 25);

        bookID5TextField.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        bookID5TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookID5TextFieldActionPerformed(evt);
            }
        });
        historyFrame.getContentPane().add(bookID5TextField);
        bookID5TextField.setBounds(830, 340, 150, 31);

        jLabel43.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Member ID:");
        historyFrame.getContentPane().add(jLabel43);
        jLabel43.setBounds(710, 380, 113, 25);

        memberID5TextField.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        memberID5TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberID5TextFieldActionPerformed(evt);
            }
        });
        historyFrame.getContentPane().add(memberID5TextField);
        memberID5TextField.setBounds(830, 380, 150, 31);

        showSpecificHistory5Button.setBackground(new java.awt.Color(51, 51, 51));
        showSpecificHistory5Button.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        showSpecificHistory5Button.setForeground(new java.awt.Color(255, 255, 255));
        showSpecificHistory5Button.setText("Show Specific History");
        showSpecificHistory5Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        showSpecificHistory5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSpecificHistory5ButtonActionPerformed(evt);
            }
        });
        historyFrame.getContentPane().add(showSpecificHistory5Button);
        showSpecificHistory5Button.setBounds(710, 430, 230, 31);

        showEntireHistory5Button.setBackground(new java.awt.Color(51, 51, 51));
        showEntireHistory5Button.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        showEntireHistory5Button.setForeground(new java.awt.Color(255, 255, 255));
        showEntireHistory5Button.setText("Show Entire History");
        showEntireHistory5Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        showEntireHistory5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showEntireHistory5ButtonActionPerformed(evt);
            }
        });
        historyFrame.getContentPane().add(showEntireHistory5Button);
        showEntireHistory5Button.setBounds(710, 470, 230, 31);

        clear5Button.setBackground(new java.awt.Color(51, 51, 51));
        clear5Button.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        clear5Button.setForeground(new java.awt.Color(255, 255, 255));
        clear5Button.setText("Clear");
        clear5Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear5ButtonActionPerformed(evt);
            }
        });
        historyFrame.getContentPane().add(clear5Button);
        clear5Button.setBounds(710, 510, 230, 31);

        backToMainMenu5Button.setBackground(new java.awt.Color(51, 51, 51));
        backToMainMenu5Button.setFont(new java.awt.Font("Book Antiqua", 1, 20));
        backToMainMenu5Button.setForeground(new java.awt.Color(255, 255, 255));
        backToMainMenu5Button.setText("Back to Main Menu");
        backToMainMenu5Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backToMainMenu5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainMenu5ButtonActionPerformed(evt);
            }
        });
        historyFrame.getContentPane().add(backToMainMenu5Button);
        backToMainMenu5Button.setBounds(710, 550, 230, 31);

        historyBackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image14 - Copy.jpg"))); // NOI18N
        historyFrame.getContentPane().add(historyBackgroundLabel);
        historyBackgroundLabel.setBounds(0, -20, 1090, 770);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System");
        setBounds(new java.awt.Rectangle(0, 0, 1086, 568));
        setIconImage(new ImageIcon("D:\\iconImage.png").getImage());
        setMinimumSize(new java.awt.Dimension(1086, 568));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        bookDetailsButton.setBackground(new java.awt.Color(240, 230, 140));
        bookDetailsButton.setFont(new java.awt.Font("Book Antiqua", 1, 36));
        bookDetailsButton.setForeground(new java.awt.Color(153, 51, 0));
        bookDetailsButton.setText("Book Details");
        bookDetailsButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bookDetailsButton.setMaximumSize(new java.awt.Dimension(250, 51));
        bookDetailsButton.setMinimumSize(new java.awt.Dimension(250, 51));
        bookDetailsButton.setPreferredSize(new java.awt.Dimension(250, 51));
        bookDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookDetailsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(bookDetailsButton);
        bookDetailsButton.setBounds(160, 130, 350, 80);

        memberDetailsButton.setBackground(new java.awt.Color(240, 230, 140));
        memberDetailsButton.setFont(bookDetailsButton.getFont());
        memberDetailsButton.setForeground(new java.awt.Color(153, 51, 0));
        memberDetailsButton.setText("Member Details");
        memberDetailsButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        memberDetailsButton.setContentAreaFilled(bookDetailsButton.isContentAreaFilled());
        memberDetailsButton.setMaximumSize(new java.awt.Dimension(250, 51));
        memberDetailsButton.setMinimumSize(new java.awt.Dimension(250, 51));
        memberDetailsButton.setPreferredSize(new java.awt.Dimension(250, 51));
        memberDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberDetailsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(memberDetailsButton);
        memberDetailsButton.setBounds(550, 130, 350, 80);

        issueBookButton.setBackground(new java.awt.Color(240, 230, 140));
        issueBookButton.setFont(bookDetailsButton.getFont());
        issueBookButton.setForeground(new java.awt.Color(153, 51, 0));
        issueBookButton.setText("Issue Book");
        issueBookButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        issueBookButton.setContentAreaFilled(bookDetailsButton.isContentAreaFilled());
        issueBookButton.setMaximumSize(new java.awt.Dimension(250, 51));
        issueBookButton.setMinimumSize(new java.awt.Dimension(250, 51));
        issueBookButton.setPreferredSize(new java.awt.Dimension(250, 51));
        issueBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBookButtonActionPerformed(evt);
            }
        });
        getContentPane().add(issueBookButton);
        issueBookButton.setBounds(160, 230, 350, 80);

        returnBookButton.setBackground(new java.awt.Color(240, 230, 140));
        returnBookButton.setFont(bookDetailsButton.getFont());
        returnBookButton.setForeground(new java.awt.Color(153, 51, 0));
        returnBookButton.setText("Return Book");
        returnBookButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        returnBookButton.setContentAreaFilled(bookDetailsButton.isContentAreaFilled());
        returnBookButton.setMaximumSize(new java.awt.Dimension(250, 51));
        returnBookButton.setMinimumSize(new java.awt.Dimension(250, 51));
        returnBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnBookButton);
        returnBookButton.setBounds(550, 230, 350, 80);

        historyButton.setBackground(new java.awt.Color(240, 230, 140));
        historyButton.setFont(bookDetailsButton.getFont());
        historyButton.setForeground(new java.awt.Color(153, 51, 0));
        historyButton.setText("History");
        historyButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        historyButton.setMaximumSize(new java.awt.Dimension(250, 51));
        historyButton.setMinimumSize(new java.awt.Dimension(250, 51));
        historyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(historyButton);
        historyButton.setBounds(160, 330, 350, 80);

        exitButton.setBackground(new java.awt.Color(240, 230, 140));
        exitButton.setFont(bookDetailsButton.getFont());
        exitButton.setForeground(new java.awt.Color(153, 51, 0));
        exitButton.setText(" Exit");
        exitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitButton.setFocusPainted(false);
        exitButton.setFocusable(false);
        exitButton.setMaximumSize(new java.awt.Dimension(250, 51));
        exitButton.setMinimumSize(new java.awt.Dimension(250, 51));
        exitButton.setRequestFocusEnabled(false);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(550, 330, 350, 80);

        mainMenuBackgroundLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenuBackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image5.jpg"))); // NOI18N
        getContentPane().add(mainMenuBackgroundLabel);
        mainMenuBackgroundLabel.setBounds(0, 0, 1070, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ButtonActionPerformed
try{
con=DriverManager.getConnection("jdbc:mysql://localhost/Project", "root", "1234");
stmt=con.createStatement();
int bookid=Integer.parseInt(bookID1TextField.getText());
String title=title1TextField.getText();
String author=author1TextField.getText();
String publisher=publisher1TextField.getText();
String isbn=ISBN1TextField.getText();
Double price=Double.parseDouble(price1TextField.getText());
String purchasedate=purchaseDate1TextField.getText();
String sql="insert into books values("+bookid+", '"+title+"', '"+author+"', '"+publisher+"', '"+isbn+"', "+price+", '"+purchasedate+"');";
System.out.println(sql);
stmt.executeUpdate(sql);
bookID1TextField.setText("");
title1TextField.setText("");
author1TextField.setText("");
publisher1TextField.setText("");
ISBN1TextField.setText("");
price1TextField.setText("");
purchaseDate1TextField.setText("");
JOptionPane.showMessageDialog(null, "Data entered.");
bookID1TextField.requestFocus();
}
catch(Exception e){
JOptionPane.showMessageDialog(null, e.getMessage());
}        // TODO add your handling code here:
}//GEN-LAST:event_add1ButtonActionPerformed

    private void bookDetailsFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_bookDetailsFrameWindowActivated
       // TODO add your handling code here:
}//GEN-LAST:event_bookDetailsFrameWindowActivated

    private void update1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ButtonActionPerformed
try{
con=DriverManager.getConnection("jdbc:mysql://localhost/Project", "root", "1234");
stmt=con.createStatement();
int bookid=Integer.parseInt(bookID1TextField.getText());
String title=title1TextField.getText();
String author=author1TextField.getText();
String publisher=publisher1TextField.getText();
String isbn=ISBN1TextField.getText();
Double price=Double.parseDouble(price1TextField.getText());
String purchasedate=purchaseDate1TextField.getText();
String sql="update books set title='"+title+"', author='"+author+"', publisher='"+publisher+"', isbn='"+isbn+"', price="+price+", purchasedate='"+purchasedate+"' where bookid="+bookid+";";
System.out.println(sql);
stmt.executeUpdate(sql);
bookID1TextField.setText("");
title1TextField.setText("");
author1TextField.setText("");
publisher1TextField.setText("");
ISBN1TextField.setText("");
price1TextField.setText("");
purchaseDate1TextField.setText("");
JOptionPane.showMessageDialog(null, "Data updated.");
bookID1TextField.requestFocus();
}
catch(Exception e){
JOptionPane.showMessageDialog(null, e.getMessage());
}        // TODO add your handling code here:
}//GEN-LAST:event_update1ButtonActionPerformed

    private void delete1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ButtonActionPerformed
try{
con=DriverManager.getConnection("jdbc:mysql://localhost/Project", "root", "1234");
stmt=con.createStatement();
int bookid=Integer.parseInt(bookID1TextField.getText());
String sql="delete from books where bookid="+bookid+";";
System.out.println(sql);
stmt.executeUpdate(sql);
bookID1TextField.setText("");
title1TextField.setText("");
author1TextField.setText("");
publisher1TextField.setText("");
ISBN1TextField.setText("");
price1TextField.setText("");
purchaseDate1TextField.setText("");
JOptionPane.showMessageDialog(null, "Data deleted.");
bookID1TextField.requestFocus();
}
catch(Exception e){
JOptionPane.showMessageDialog(null, e.getMessage());
}        // TODO add your handling code here:
}//GEN-LAST:event_delete1ButtonActionPerformed

    private void bookID1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookID1TextFieldActionPerformed
title1TextField.requestFocus();        // TODO add your handling code here:
}//GEN-LAST:event_bookID1TextFieldActionPerformed

    private void title1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_title1TextFieldActionPerformed
author1TextField.requestFocus();        // TODO add your handling code here:
}//GEN-LAST:event_title1TextFieldActionPerformed

    private void author1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_author1TextFieldActionPerformed
publisher1TextField.requestFocus();        // TODO add your handling code here:
}//GEN-LAST:event_author1TextFieldActionPerformed

    private void publisher1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publisher1TextFieldActionPerformed
ISBN1TextField.requestFocus();        // TODO add your handling code here:
}//GEN-LAST:event_publisher1TextFieldActionPerformed

    private void ISBN1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISBN1TextFieldActionPerformed
purchaseDate1TextField.requestFocus();       // TODO add your handling code here:
}//GEN-LAST:event_ISBN1TextFieldActionPerformed

    private void price1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price1TextFieldActionPerformed
         // TODO add your handling code here:
}//GEN-LAST:event_price1TextFieldActionPerformed

    private void enquire1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enquire1ButtonActionPerformed
try{
con=DriverManager.getConnection("jdbc:mysql://localhost/Project", "root", "1234");
stmt=con.createStatement();
int bookid=Integer.parseInt(bookID1TextField.getText());
String sql="select * from books where bookid="+bookid+";";
System.out.println(sql);
rs=stmt.executeQuery(sql);
rs.first();
title1TextField.setText(rs.getString("Title"));
author1TextField.setText(rs.getString("Author"));
publisher1TextField.setText(rs.getString("Publisher"));
ISBN1TextField.setText(rs.getString("ISBN"));
price1TextField.setText(""+rs.getDouble("Price"));
purchaseDate1TextField.setText(""+rs.getDate("PurchaseDate"));
}
catch(Exception e){
JOptionPane.showMessageDialog(null, e.getMessage());
}           // TODO add your handling code here:
}//GEN-LAST:event_enquire1ButtonActionPerformed

    private void clear1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear1ButtonActionPerformed
bookID1TextField.setText("");
title1TextField.setText("");
author1TextField.setText("");
publisher1TextField.setText("");
ISBN1TextField.setText("");
price1TextField.setText("");
purchaseDate1TextField.setText("");
bookID1TextField.requestFocus();// TODO add your handling code here:
}//GEN-LAST:event_clear1ButtonActionPerformed

    private void enquire2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enquire2ButtonActionPerformed
try{
con=DriverManager.getConnection("jdbc:mysql://localhost/Project", "root", "1234");
stmt=con.createStatement();
int memberid=Integer.parseInt(memberID2TextField.getText());
String sql="select * from members where memberid="+memberid+";";
System.out.println(sql);
rs=stmt.executeQuery(sql);
rs.first();
name2TextField.setText(rs.getString("Name"));
class2ComboBox.setSelectedItem(rs.getString("Class"));
section2ComboBox.setSelectedItem(rs.getString("Section"));
}
catch(Exception e){
JOptionPane.showMessageDialog(null, e.getMessage());
}            // TODO add your handling code here:
}//GEN-LAST:event_enquire2ButtonActionPerformed

    private void add2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add2ButtonActionPerformed
try{
con=DriverManager.getConnection("jdbc:mysql://localhost/Project", "root", "1234");
stmt=con.createStatement();
int memberid=Integer.parseInt(memberID2TextField.getText());
String name=name2TextField.getText();
String c=(String)class2ComboBox.getSelectedItem();
String section=(String)section2ComboBox.getSelectedItem();
String sql="insert into members values("+memberid+", '"+name+"', "+c+", '"+section+"');";
System.out.println(sql);
stmt.executeUpdate(sql);
memberID2TextField.setText("");
name2TextField.setText("");
class2ComboBox.setSelectedIndex(0);
section2ComboBox.setSelectedIndex(0);
JOptionPane.showMessageDialog(null, "Data entered.");
memberID2TextField.requestFocus();
}
catch(Exception e){
JOptionPane.showMessageDialog(null, e.getMessage());
}        // TODO add your handling code here:
}//GEN-LAST:event_add2ButtonActionPerformed

    private void clear2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear2ButtonActionPerformed
memberID2TextField.setText("");
name2TextField.setText("");
class2ComboBox.setSelectedIndex(0);
section2ComboBox.setSelectedIndex(0);
memberID2TextField.requestFocus();// TODO add your handling code here:
}//GEN-LAST:event_clear2ButtonActionPerformed

    private void update2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update2ButtonActionPerformed
try{
con=DriverManager.getConnection("jdbc:mysql://localhost/Project", "root", "1234");
stmt=con.createStatement();
int memberid=Integer.parseInt(memberID2TextField.getText());
String name=name2TextField.getText();
String c=(String)class2ComboBox.getSelectedItem();
String section=(String)section2ComboBox.getSelectedItem();
String sql="update members set name='"+name+"', class="+c+", section='"+section+"' where memberid="+memberid+";";
System.out.println(sql);
stmt.executeUpdate(sql);
memberID2TextField.setText("");
name2TextField.setText("");
class2ComboBox.setSelectedIndex(0);
section2ComboBox.setSelectedIndex(0);
JOptionPane.showMessageDialog(null, "Data updated.");
memberID2TextField.requestFocus();
}
catch(Exception e){
JOptionPane.showMessageDialog(null, e.getMessage());
}        // TODO add your handling code here:
}//GEN-LAST:event_update2ButtonActionPerformed

    private void delete2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete2ButtonActionPerformed
try{
con=DriverManager.getConnection("jdbc:mysql://localhost/Project", "root", "1234");
stmt=con.createStatement();
int memberid=Integer.parseInt(memberID2TextField.getText());
String sql="delete from members where memberid="+memberid+";";
System.out.println(sql);
stmt.executeUpdate(sql);
memberID2TextField.setText("");
name2TextField.setText("");
class2ComboBox.setSelectedIndex(0);
section2ComboBox.setSelectedIndex(0);
JOptionPane.showMessageDialog(null, "Data deleted.");
memberID2TextField.requestFocus();
}
catch(Exception e){
JOptionPane.showMessageDialog(null, e.getMessage());
}        // TODO add your handling code here:
}//GEN-LAST:event_delete2ButtonActionPerformed

    private void return1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return1ButtonActionPerformed
bookDetailsFrame.dispose();
bookID1TextField.setText("");
title1TextField.setText("");
author1TextField.setText("");
publisher1TextField.setText("");
ISBN1TextField.setText("");
price1TextField.setText("");
purchaseDate1TextField.setText("");
this.setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_return1ButtonActionPerformed

    private void return2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return2ButtonActionPerformed
memberDetailsFrame.dispose();
memberID2TextField.setText("");
name2TextField.setText("");
class2ComboBox.setSelectedIndex(0);
section2ComboBox.setSelectedIndex(0);
this.setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_return2ButtonActionPerformed

    private void return3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return3ButtonActionPerformed
issueBookFrame.dispose();
bookID3TextField.setText("");
memberID3TextField.setText("");
dateOfIssue3TextField.setText("");
title3OutputLabel.setText("");
author3OutputLabel.setText("");
name3OutputLabel.setText("");
class3OutputLabel.setText("");
section3OutputLabel.setText("");
this.setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_return3ButtonActionPerformed

    private void return4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return4ButtonActionPerformed
returnBookFrame.dispose();
bookID4TextField.setText("");
dateOfReturn4TextField.setText("");
title4OutputLabel.setText("");
author4OutputLabel.setText("");
name4OutputLabel.setText("");
class4OutputLabel.setText("");
section4OutputLabel.setText("");
dateOfIssue4OutputLabel.setText("");
memberID4OutputLabel.setText("");
this.setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_return4ButtonActionPerformed

    private void bookID3TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookID3TextFieldActionPerformed
try{
con=DriverManager.getConnection("jdbc:mysql://localhost/Project", "root", "1234");
stmt=con.createStatement();
int bookid=Integer.parseInt(bookID3TextField.getText());
String sql="select * from books where bookid="+bookid+";";
System.out.println(sql);
rs=stmt.executeQuery(sql);
rs.first();
title3OutputLabel.setText(rs.getString("Title"));
author3OutputLabel.setText(rs.getString("Author"));
memberID3TextField.requestFocus();
}
catch(Exception e){
JOptionPane.showMessageDialog(null, e.getMessage());
}        // TODO add your handling code here:
}//GEN-LAST:event_bookID3TextFieldActionPerformed

    private void memberID3TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberID3TextFieldActionPerformed
try{
con=DriverManager.getConnection("jdbc:mysql://localhost/Project", "root", "1234");
stmt=con.createStatement();
int memberid=Integer.parseInt(memberID3TextField.getText());
String sql="select * from members where memberid="+memberid+";";
System.out.println(sql);
rs=stmt.executeQuery(sql);
rs.first();
name3OutputLabel.setText(rs.getString("Name"));
class3OutputLabel.setText(rs.getString("Class"));
section3OutputLabel.setText(rs.getString("Section"));
dateOfIssue3TextField.requestFocus();
}
catch(Exception e){
JOptionPane.showMessageDialog(null, e.getMessage());
}        // TODO add your handling code here:
}//GEN-LAST:event_memberID3TextFieldActionPerformed

    private void today3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_today3ButtonActionPerformed
try{
con=DriverManager.getConnection("jdbc:mysql://localhost/Project", "root", "1234");
stmt=con.createStatement();
String sql="Select curdate();";
System.out.println(sql);
rs=stmt.executeQuery(sql);
rs.first();
dateOfIssue3TextField.setText(rs.getString(1));
}
catch(Exception e){
JOptionPane.showMessageDialog(null, e.getMessage());
}        // TODO add your handling code here:
}//GEN-LAST:event_today3ButtonActionPerformed

    private void issueBook3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBook3ButtonActionPerformed
try{
con=DriverManager.getConnection("jdbc:mysql://localhost/Project", "root", "1234");
stmt=con.createStatement();
int bookid=Integer.parseInt(bookID3TextField.getText());
rs=stmt.executeQuery("Select title from books where bookid="+bookid+";");
rs.first();
String title=rs.getString("Title");
int memberid=Integer.parseInt(memberID3TextField.getText());
rs=stmt.executeQuery("Select name from members where memberid="+memberid+";");
rs.first();
String name=rs.getString("Name");
String issuedate=dateOfIssue3TextField.getText();
String sql1="Select * from booktrn where bookid="+bookid+" and returndate is null;";
rs=stmt.executeQuery(sql1);
if(rs.next()){
JOptionPane.showMessageDialog(null, "This book has already been issued.");
}
else{
String sql="insert into BookTRN (bookid, title, memberid, name, issuedate) values("+bookid+", '"+title+"', "+memberid+", '"+name+"', '"+issuedate+"');";
System.out.println(sql);
stmt.executeUpdate(sql);
bookID3TextField.setText("");
memberID3TextField.setText("");
dateOfIssue3TextField.setText("");
title3OutputLabel.setText("");
author3OutputLabel.setText("");
name3OutputLabel.setText("");
class3OutputLabel.setText("");
section3OutputLabel.setText("");
JOptionPane.showMessageDialog(null, "Book issued.");
bookID3TextField.requestFocus();
}
}
catch(Exception e){
JOptionPane.showMessageDialog(null, e.getMessage());
}        // TODO add your handling code here:
}//GEN-LAST:event_issueBook3ButtonActionPerformed

    private void clear3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear3ButtonActionPerformed
	bookID3TextField.setText("");
	memberID3TextField.setText("");
	dateOfIssue3TextField.setText("");
	title3OutputLabel.setText("");
	author3OutputLabel.setText("");
	name3OutputLabel.setText("");
	class3OutputLabel.setText("");
	section3OutputLabel.setText("");
	bookID3TextField.requestFocus();// TODO add your handling code here:
}//GEN-LAST:event_clear3ButtonActionPerformed

    private void clear4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear4ButtonActionPerformed
bookID4TextField.setText("");
dateOfReturn4TextField.setText("");
title4OutputLabel.setText("");
author4OutputLabel.setText("");
name4OutputLabel.setText("");
class4OutputLabel.setText("");
section4OutputLabel.setText("");
dateOfIssue4OutputLabel.setText("");
memberID4OutputLabel.setText("");
bookID4TextField.requestFocus();
// TODO add your handling code here:
}//GEN-LAST:event_clear4ButtonActionPerformed

    private void today4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_today4ButtonActionPerformed
try{
con=DriverManager.getConnection("jdbc:mysql://localhost/Project", "root", "1234");
stmt=con.createStatement();
String sql="select curdate();";
System.out.println(sql);
rs=stmt.executeQuery(sql);
rs.first();
dateOfReturn4TextField.setText(rs.getString(1));
}
catch(Exception e){
JOptionPane.showMessageDialog(null, e.getMessage());
}        // TODO add your handling code here:
}//GEN-LAST:event_today4ButtonActionPerformed

    private void returnBook4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBook4ButtonActionPerformed
try{
con=DriverManager.getConnection("jdbc:mysql://localhost/Project", "root", "1234");
stmt=con.createStatement();
int bookid=Integer.parseInt(bookID4TextField.getText());
String returndate=dateOfReturn4TextField.getText();
String sql1="Select * from booktrn where bookid="+bookid+" and returndate is null;";
rs=stmt.executeQuery(sql1);
if(rs.next()){
String sql="update BookTRN set returndate='"+returndate+"' where bookid="+bookid+" and returndate is null;";
System.out.println(sql);
stmt.executeUpdate(sql);
bookID4TextField.setText("");
dateOfReturn4TextField.setText("");
title4OutputLabel.setText("");
author4OutputLabel.setText("");
name4OutputLabel.setText("");
class4OutputLabel.setText("");
section4OutputLabel.setText("");
dateOfIssue4OutputLabel.setText("");
memberID4OutputLabel.setText("");
JOptionPane.showMessageDialog(null, "Book returned.");
bookID4TextField.requestFocus();
}
else{JOptionPane.showMessageDialog(null, "This book has already been returned, or has not been issued yet, or does not exist.");
}
}
catch(Exception e){
JOptionPane.showMessageDialog(null, e.getMessage());
}        // TODO add your handling code here:
}//GEN-LAST:event_returnBook4ButtonActionPerformed

    private void bookID4TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookID4TextFieldActionPerformed
try{
con=DriverManager.getConnection("jdbc:mysql://localhost/Project", "root", "1234");
stmt=con.createStatement();
int bookid=Integer.parseInt(bookID4TextField.getText());
String sql="Select booktrn.bookid, books.title, author, booktrn.memberid, members.name, class, section, issuedate from books, members, booktrn where books.bookid=booktrn.bookid and members.memberid=booktrn.memberid and booktrn.bookid="+bookid+";";
System.out.println(sql);
rs=stmt.executeQuery(sql);
rs.first();
title4OutputLabel.setText(rs.getString("Title"));
author4OutputLabel.setText(rs.getString("Author"));
memberID4OutputLabel.setText(rs.getString("MemberID"));
name4OutputLabel.setText(rs.getString("Name"));
class4OutputLabel.setText(rs.getString("Class"));
section4OutputLabel.setText(rs.getString("Section"));
dateOfIssue4OutputLabel.setText(rs.getString("IssueDate"));
dateOfReturn4TextField.requestFocus();
}
catch(Exception e){
JOptionPane.showMessageDialog(null, e.getMessage());
}         // TODO add your handling code here:
}//GEN-LAST:event_bookID4TextFieldActionPerformed

    private void memberID2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberID2TextFieldActionPerformed
name2TextField.requestFocus();        // TODO add your handling code here:
}//GEN-LAST:event_memberID2TextFieldActionPerformed

    private void clear5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear5ButtonActionPerformed
bookID5TextField.setText("");
memberID5TextField.setText("");
tm.setRowCount(0);
bookID5TextField.requestFocus();// TODO add your handling code here:
}//GEN-LAST:event_clear5ButtonActionPerformed

    private void historyFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_historyFrameWindowActivated
tm=(DefaultTableModel)history5Table.getModel();
bookID5TextField.requestFocus();
// TODO add your handling code here:
}//GEN-LAST:event_historyFrameWindowActivated

    private void showSpecificHistory5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSpecificHistory5ButtonActionPerformed
try{
tm.setRowCount(0);
con=DriverManager.getConnection("jdbc:mysql://localhost/Project", "root", "1234");
stmt=con.createStatement();
String b=bookID5TextField.getText();
String m=memberID5TextField.getText();
String sql="";
if(b.equals("")&&m.equals("")){
JOptionPane.showMessageDialog(null, "Please enter Book ID and/or Member ID to view specific history.");
bookID5TextField.requestFocus();
}
else{
if(b.equals("")){
int memberid=Integer.parseInt(m);
sql="Select * from BookTRN where memberid="+memberid+";";
}
else if(m.equals("")){
int bookid=Integer.parseInt(b);
sql="Select * from BookTRN where bookid="+bookid+";";
}
else{
int bookid=Integer.parseInt(b);
int memberid=Integer.parseInt(m);
sql="Select * from BookTRN where bookid="+bookid+" and memberid="+memberid+";";
}
rs=stmt.executeQuery(sql);
while(rs.next()){
tm.addRow(new Object [] {rs.getInt("BookID"), rs.getString("Title"), rs.getInt("MemberID"), rs.getString("Name"), rs.getString("IssueDate"), rs.getString("ReturnDate")});
}
bookID5TextField.requestFocus();
}
}
catch(Exception e){
JOptionPane.showMessageDialog(null, e.getMessage());
}        // TODO add your handling code here:
}//GEN-LAST:event_showSpecificHistory5ButtonActionPerformed

    private void showEntireHistory5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showEntireHistory5ButtonActionPerformed
bookID5TextField.setText("");
memberID5TextField.setText("");
try{
tm.setRowCount(0);
con=DriverManager.getConnection("jdbc:mysql://localhost/Project", "root", "1234");
stmt=con.createStatement();
String sql="Select * from BookTRN";
rs=stmt.executeQuery(sql);
while(rs.next()){
tm.addRow(new Object [] {rs.getInt("BookID"), rs.getString("Title"), rs.getInt("MemberID"), rs.getString("Name"), rs.getString("IssueDate"), rs.getString("ReturnDate")});
}
bookID5TextField.requestFocus();
}
catch(Exception e){
JOptionPane.showMessageDialog(null, e.getMessage());
}     // TODO add your handling code here:
}//GEN-LAST:event_showEntireHistory5ButtonActionPerformed

    private void backToMainMenu5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMainMenu5ButtonActionPerformed
historyFrame.dispose();
bookID5TextField.setText("");
memberID5TextField.setText("");
tm.setRowCount(0); 
this.setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_backToMainMenu5ButtonActionPerformed

    private void bookID5TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookID5TextFieldActionPerformed
memberID5TextField.requestFocus();        // TODO add your handling code here:
}//GEN-LAST:event_bookID5TextFieldActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowActivated

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);        // TODO add your handling code here:
}//GEN-LAST:event_exitButtonActionPerformed

    private void historyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyButtonActionPerformed
        this.dispose();
        historyFrame.setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_historyButtonActionPerformed

    private void returnBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookButtonActionPerformed
        this.dispose();
        returnBookFrame.setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_returnBookButtonActionPerformed

    private void issueBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBookButtonActionPerformed
        this.dispose();
        issueBookFrame.setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_issueBookButtonActionPerformed

    private void memberDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberDetailsButtonActionPerformed
        this.dispose();
        memberDetailsFrame.setVisible(true);        // TODO add your handling code here:
}//GEN-LAST:event_memberDetailsButtonActionPerformed

    private void bookDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookDetailsButtonActionPerformed
        this.dispose();
        bookDetailsFrame.setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_bookDetailsButtonActionPerformed

    private void purchaseDate1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseDate1TextFieldActionPerformed
price1TextField.requestFocus();        // TODO add your handling code here:
}//GEN-LAST:event_purchaseDate1TextFieldActionPerformed

    private void name2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name2TextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_name2TextFieldActionPerformed

    private void dateOfReturn4TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateOfReturn4TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateOfReturn4TextFieldActionPerformed

    private void memberID5TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberID5TextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_memberID5TextFieldActionPerformed

    private void class2ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_class2ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_class2ComboBoxActionPerformed

    private void section2ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_section2ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_section2ComboBoxActionPerformed

    private void dateOfIssue3TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateOfIssue3TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateOfIssue3TextFieldActionPerformed

    /**
    * @param args the command line arguments
    */

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryManagementSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookIssueBackgroundLabel;
    private javax.swing.JTextField ISBN1TextField;
    private javax.swing.JLabel TitleLable;
    private javax.swing.JButton add1Button;
    private javax.swing.JButton add2Button;
    private javax.swing.JTextField author1TextField;
    private javax.swing.JLabel author3OutputLabel;
    private javax.swing.JLabel author4OutputLabel;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JButton backToMainMenu5Button;
    private javax.swing.JLabel bookDetailsBackgroundlabel;
    private javax.swing.JButton bookDetailsButton;
    private javax.swing.JFrame bookDetailsFrame;
    private javax.swing.JPanel bookDetailsPanel;
    private javax.swing.JTextField bookID1TextField;
    private javax.swing.JTextField bookID3TextField;
    private javax.swing.JTextField bookID4TextField;
    private javax.swing.JTextField bookID5TextField;
    private javax.swing.JLabel bookIdLabel;
    private javax.swing.JPanel bookIssuePanel;
    private javax.swing.JLabel bookReceiptBackgroundLabel;
    private javax.swing.JPanel bookReceiptPanel;
    private javax.swing.JComboBox class2ComboBox;
    private javax.swing.JLabel class3OutputLabel;
    private javax.swing.JLabel class4OutputLabel;
    private javax.swing.JButton clear1Button;
    private javax.swing.JButton clear2Button;
    private javax.swing.JButton clear3Button;
    private javax.swing.JButton clear4Button;
    private javax.swing.JButton clear5Button;
    private javax.swing.JTextField dateOfIssue3TextField;
    private javax.swing.JLabel dateOfIssue4OutputLabel;
    private javax.swing.JTextField dateOfReturn4TextField;
    private javax.swing.JButton delete1Button;
    private javax.swing.JButton delete2Button;
    private javax.swing.JButton enquire1Button;
    private javax.swing.JButton enquire2Button;
    private javax.swing.JButton exitButton;
    private javax.swing.JTable history5Table;
    private javax.swing.JLabel historyBackgroundLabel;
    private javax.swing.JButton historyButton;
    private javax.swing.JFrame historyFrame;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JButton issueBook3Button;
    private javax.swing.JButton issueBookButton;
    private javax.swing.JFrame issueBookFrame;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mainMenuBackgroundLabel;
    private javax.swing.JButton memberDetailsButton;
    private javax.swing.JFrame memberDetailsFrame;
    private javax.swing.JPanel memberDetailsPanel;
    private javax.swing.JTextField memberID2TextField;
    private javax.swing.JTextField memberID3TextField;
    private javax.swing.JLabel memberID4OutputLabel;
    private javax.swing.JTextField memberID5TextField;
    private javax.swing.JLabel memberdetailsbackgroundLabel;
    private javax.swing.JTextField name2TextField;
    private javax.swing.JLabel name3OutputLabel;
    private javax.swing.JLabel name4OutputLabel;
    private javax.swing.JTextField price1TextField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField publisher1TextField;
    private javax.swing.JLabel publisherLabel;
    private javax.swing.JTextField purchaseDate1TextField;
    private javax.swing.JLabel purchaseDateLabel;
    private javax.swing.JButton return1Button;
    private javax.swing.JButton return2Button;
    private javax.swing.JButton return3Button;
    private javax.swing.JButton return4Button;
    private javax.swing.JButton returnBook4Button;
    private javax.swing.JButton returnBookButton;
    private javax.swing.JFrame returnBookFrame;
    private javax.swing.JComboBox section2ComboBox;
    private javax.swing.JLabel section3OutputLabel;
    private javax.swing.JLabel section4OutputLabel;
    private javax.swing.JButton showEntireHistory5Button;
    private javax.swing.JButton showSpecificHistory5Button;
    private javax.swing.JTextField title1TextField;
    private javax.swing.JLabel title3OutputLabel;
    private javax.swing.JLabel title4OutputLabel;
    private javax.swing.JButton today3Button;
    private javax.swing.JButton today4Button;
    private javax.swing.JButton update1Button;
    private javax.swing.JButton update2Button;
    // End of variables declaration//GEN-END:variables

}
